### ISSUE TITLE
Fatal Error When Trying to Build on Linux Mint 18.3

### ISSUE THREAD

**Issue by WulftheNordicRanger** [BlindMindStudios/StarRuler2-Source#7]
First off, thank you for releasing this to the community! I look forward to playing this once it gets built.
Anyways when I was trying to build this I got a fatal error. Here's the output from the terminal

source/os/source/threads.cpp
source/os/source/threads_gcc.cpp
source/os/source/files.cpp
source/os/source/files_linux.cpp
source/os/source/files_linux.cpp: In function ‘std::__cxx11::string getWorkingDirectory()’:
source/os/source/files_linux.cpp:18:22: warning: ignoring return value of ‘char* getcwd(char*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  getcwd(buffer, 1024);
                      ^
source/os/source/virtual_asm_linux.cpp
source/os/source/virtual_asm_x64.cpp
source/sound/source/CSound.cpp
source/sound/source/CSoundDevice.cpp
source/sound/source/CSoundSource.cpp
source/sound/source/CStreamSound.cpp
source/sound/source/CSSOgg.cpp
In file included from ./source/sound/ogg/ogg.h:25:0,
                 from source/sound/source/CSSOgg.cpp:5:
./source/sound/ogg/os_types.h:135:32: fatal error: ogg/config_types.h: No such file or directory
compilation terminated.
source/sound/gcc/Makefile:92: recipe for target 'obj/lin64/sound/CSSOgg.o' failed
make[1]: *** [obj/lin64/sound/CSSOgg.o] Error 1
source/linux/Makefile:326: recipe for target 'makelibs' failed
make: *** [makelibs] Error 2

**Comment by miquelramirez** [comment]
Looks like ```libogg``` headers aren't installed on a prefix the makefile script knows about.

**Comment by WulftheNordicRanger** [comment]
I managed to solve the issue by installing liboggdev. I still need to make it detect free type 2 but I think that this can be closed now.
